castleXP:
    location:
        x:
        y:
        z:
        world:
    teleport:
castleGold:
    location:
        x:
        y:
        z:
        world:
    teleport:
castleMoney:
    location:
        x:
        y:
        z:
        world:
    teleport:
castleDiamond:
    location:
        x:
        y:
        z:
        world:
    teleport:
rewards:
    xp: 80
    gold: 10
    money: 500
    diamond: 5
    power: 10
